Update nan and node-pre-gyp to fix build error
With the old version of nan, we were getting this error:

  CXX(target) Release/obj.target/mmap_io/src/mmap-io.o
In file included from ../src/mmap-io.cc:10:
In file included from ../node_modules/nan/nan.h:2884:
../node_modules/nan/nan_typedarray_contents.h:34:43: error: no member named 'GetContents' in 'v8::ArrayBuffer'
      data   = static_cast<char*>(buffer->GetContents().Data()) + byte_offset;
                                  ~~~~~~~~^

Updating to nan 2.16.0 fixes this issue.